import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'lib/firebase_options.dart';
import 'lib/services/firestore_service.dart';
import 'lib/models/topic_model.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  print('Firebase initialized successfully');

  final firestoreService = FirestoreService();

  final iconMap = {
    'smartphone': Icons.smartphone,
    'settings_applications': Icons.settings_applications,
    'cloud': Icons.cloud,
    'data_exploration_rounded': Icons.data_exploration_rounded,
    'animation': Icons.animation,
    'design_services': Icons.design_services,
    'devices': Icons.devices,
    'storage': Icons.storage,
    'bug_report': Icons.bug_report,
    'publish': Icons.publish,
    'code': Icons.code,
    'account_tree': Icons.account_tree,
    'sync': Icons.sync,
    'accessibility': Icons.accessibility,
    'lock': Icons.lock,
    'schedule': Icons.schedule,
    'chat': Icons.chat,
    'account_balance_wallet': Icons.account_balance_wallet,
    'psychology': Icons.psychology,
    'science': Icons.science,
    'biotech': Icons.biotech,
    'local_florist': Icons.local_florist,
    'eco': Icons.eco,
    'public': Icons.public,
    'menu_book': Icons.menu_book,
    'edit': Icons.edit,
    'palette': Icons.palette,
    'calculate': Icons.calculate,
    'architecture': Icons.architecture,
    'bar_chart': Icons.bar_chart,
    'functions': Icons.functions,
    'store': Icons.store,
    'trending_up': Icons.trending_up,
    'savings': Icons.savings,
    'business_center': Icons.business_center,
    'security': Icons.security,
    'mail': Icons.mail,
    'search': Icons.search,
    'cloud_upload': Icons.cloud_upload,
    'share': Icons.share,
    'vpn_key': Icons.vpn_key,
    'fingerprint': Icons.fingerprint,
    'lightbulb': Icons.lightbulb,
    'explore': Icons.explore,
    'grid_on': Icons.grid_on,
    'troubleshoot': Icons.troubleshoot,
    'hub': Icons.hub,
    'science_outlined': Icons.science_outlined,
    'data_object': Icons.data_object,
    'engineering': Icons.engineering,
    'straighten': Icons.straighten,
    'electrical_services': Icons.electrical_services,
    'smart_toy': Icons.smart_toy,
  };

  final topics = [
    Topic(
      id: '1',
      title: 'Flutter Basics',
      description: 'Learn the fundamentals of Flutter development',
      category: 'Programming',
      icon: iconMap['smartphone']!,
      estimatedMinutes: 30,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '2',
      title: 'State Management',
      description: 'Master state management with Provider and Riverpod',
      category: 'Programming',
      icon: iconMap['settings_applications']!,
      estimatedMinutes: 45,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '3',
      title: 'REST APIs',
      description: 'Understanding and working with REST APIs',
      category: 'Programming',
      icon: iconMap['cloud']!,
      estimatedMinutes: 40,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '4',
      title: 'Firebase Integration',
      description: 'Integrate Firebase services in your Flutter app',
      category: 'Programming',
      icon: iconMap['data_exploration_rounded']!,
      estimatedMinutes: 50,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '5',
      title: 'Custom Animations',
      description: 'Create beautiful custom animations in Flutter',
      category: 'Programming',
      icon: iconMap['animation']!,
      estimatedMinutes: 35,
      difficulty: 'Advanced',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '6',
      title: 'Material Design',
      description: 'Implement Material Design principles',
      category: 'Programming',
      icon: iconMap['design_services']!,
      estimatedMinutes: 25,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '7',
      title: 'Responsive Layouts',
      description: 'Build responsive UIs for all screen sizes',
      category: 'Programming',
      icon: iconMap['devices']!,
      estimatedMinutes: 30,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '8',
      title: 'Local Database',
      description: 'Work with SQLite and local storage',
      category: 'Programming',
      icon: iconMap['storage']!,
      estimatedMinutes: 40,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '9',
      title: 'Testing in Flutter',
      description: 'Write unit, widget, and integration tests',
      category: 'Programming',
      icon: iconMap['bug_report']!,
      estimatedMinutes: 45,
      difficulty: 'Advanced',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '10',
      title: 'App Deployment',
      description: 'Deploy your app to App Store and Play Store',
      category: 'Programming',
      icon: iconMap['publish']!,
      estimatedMinutes: 60,
      difficulty: 'Advanced',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '11',
      title: 'Dart Fundamentals',
      description: 'Syntax, types, collections, and async in Dart',
      category: 'Programming',
      icon: iconMap['code']!,
      estimatedMinutes: 40,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '12',
      title: 'Clean Architecture',
      description: 'Layered architecture patterns for Flutter apps',
      category: 'Programming',
      icon: iconMap['account_tree']!,
      estimatedMinutes: 50,
      difficulty: 'Advanced',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '13',
      title: 'CI/CD with GitHub Actions',
      description: 'Automate build, test and deploy for Flutter',
      category: 'Programming',
      icon: iconMap['sync']!,
      estimatedMinutes: 55,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '14',
      title: 'Accessibility',
      description: 'Build accessible apps with a11y best practices',
      category: 'Programming',
      icon: iconMap['accessibility']!,
      estimatedMinutes: 30,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '15',
      title: 'Security Basics',
      description: 'Secure storage, auth, and network in apps',
      category: 'Programming',
      icon: iconMap['lock']!,
      estimatedMinutes: 40,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '16',
      title: 'Time Management',
      description: 'Master productivity and time organization skills',
      category: 'Life Skills',
      icon: iconMap['schedule']!,
      estimatedMinutes: 35,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '17',
      title: 'Communication Skills',
      description: 'Effective verbal and written communication',
      category: 'Life Skills',
      icon: iconMap['chat']!,
      estimatedMinutes: 40,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '18',
      title: 'Financial Literacy',
      description: 'Budgeting, saving, and basic personal finance',
      category: 'Life Skills',
      icon: iconMap['account_balance_wallet']!,
      estimatedMinutes: 45,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '19',
      title: 'Critical Thinking',
      description: 'Develop analytical and problem-solving skills',
      category: 'Life Skills',
      icon: iconMap['psychology']!,
      estimatedMinutes: 40,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '20',
      title: 'Physics Fundamentals',
      description: 'Newton\'s laws, energy, and motion',
      category: 'Science',
      icon: iconMap['science']!,
      estimatedMinutes: 50,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '21',
      title: 'Chemistry Basics',
      description: 'Elements, compounds, and chemical reactions',
      category: 'Science',
      icon: iconMap['biotech']!,
      estimatedMinutes: 45,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '22',
      title: 'Biology Introduction',
      description: 'Cell structure, genetics, and ecosystems',
      category: 'Science',
      icon: iconMap['local_florist']!,
      estimatedMinutes: 40,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '23',
      title: 'Environmental Science',
      description: 'Climate change, sustainability, and ecology',
      category: 'Science',
      icon: iconMap['eco']!,
      estimatedMinutes: 35,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '24',
      title: 'World History',
      description: 'Major civilizations and historical events',
      category: 'Arts & Humanities',
      icon: iconMap['public']!,
      estimatedMinutes: 50,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '25',
      title: 'Philosophy Basics',
      description: 'Ethics, logic, and major philosophical ideas',
      category: 'Arts & Humanities',
      icon: iconMap['menu_book']!,
      estimatedMinutes: 45,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '26',
      title: 'Creative Writing',
      description: 'Storytelling, character development, and narrative',
      category: 'Arts & Humanities',
      icon: iconMap['edit']!,
      estimatedMinutes: 40,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '27',
      title: 'Art History',
      description: 'Major art movements and influential artists',
      category: 'Arts & Humanities',
      icon: iconMap['palette']!,
      estimatedMinutes: 35,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '28',
      title: 'Algebra Fundamentals',
      description: 'Equations, variables, and functions',
      category: 'Math',
      icon: iconMap['calculate']!,
      estimatedMinutes: 45,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '29',
      title: 'Geometry Basics',
      description: 'Shapes, angles, and spatial reasoning',
      category: 'Math',
      icon: iconMap['architecture']!,
      estimatedMinutes: 40,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '30',
      title: 'Statistics & Probability',
      description: 'Data analysis and probability theory',
      category: 'Math',
      icon: iconMap['bar_chart']!,
      estimatedMinutes: 50,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '31',
      title: 'Calculus Introduction',
      description: 'Limits, derivatives, and integrals',
      category: 'Math',
      icon: iconMap['functions']!,
      estimatedMinutes: 60,
      difficulty: 'Advanced',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '32',
      title: 'Microeconomics',
      description: 'Supply, demand, and market structures',
      category: 'Economics',
      icon: iconMap['store']!,
      estimatedMinutes: 45,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '33',
      title: 'Macroeconomics',
      description: 'GDP, inflation, and economic policies',
      category: 'Economics',
      icon: iconMap['trending_up']!,
      estimatedMinutes: 50,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '34',
      title: 'Personal Finance',
      description: 'Investing, retirement planning, and wealth building',
      category: 'Economics',
      icon: iconMap['savings']!,
      estimatedMinutes: 40,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '35',
      title: 'Business Economics',
      description: 'Cost analysis, pricing strategies, and profit',
      category: 'Economics',
      icon: iconMap['business_center']!,
      estimatedMinutes: 45,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '36',
      title: 'Internet Safety',
      description: 'Privacy, online security, and safe browsing',
      category: 'Digital Literacy',
      icon: iconMap['security']!,
      estimatedMinutes: 30,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '37',
      title: 'Email & Communication',
      description: 'Professional emails, online etiquette, and tools',
      category: 'Digital Literacy',
      icon: iconMap['mail']!,
      estimatedMinutes: 25,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '38',
      title: 'Search Skills',
      description: 'Effective web searching and information evaluation',
      category: 'Digital Literacy',
      icon: iconMap['search']!,
      estimatedMinutes: 20,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '39',
      title: 'Cloud Storage',
      description: 'Google Drive, Dropbox, and file management',
      category: 'Digital Literacy',
      icon: iconMap['cloud_upload']!,
      estimatedMinutes: 30,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '40',
      title: 'Social Media Literacy',
      description: 'Responsible use and avoiding misinformation',
      category: 'Digital Literacy',
      icon: iconMap['share']!,
      estimatedMinutes: 35,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '41',
      title: 'Password Management',
      description: 'Creating strong passwords and using managers',
      category: 'Digital Literacy',
      icon: iconMap['vpn_key']!,
      estimatedMinutes: 25,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '42',
      title: 'Digital Footprint',
      description: 'Online reputation and personal branding',
      category: 'Digital Literacy',
      icon: iconMap['fingerprint']!,
      estimatedMinutes: 30,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '43',
      title: 'Logical Reasoning',
      description: 'Deductive and inductive reasoning patterns',
      category: 'Problem Solving',
      icon: iconMap['lightbulb']!,
      estimatedMinutes: 35,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '44',
      title: 'Algorithmic Thinking',
      description: 'Breaking down problems into steps',
      category: 'Problem Solving',
      icon: iconMap['explore']!,
      estimatedMinutes: 40,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '45',
      title: 'Pattern Recognition',
      description: 'Identifying patterns in data and sequences',
      category: 'Problem Solving',
      icon: iconMap['grid_on']!,
      estimatedMinutes: 30,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '46',
      title: 'Decision Trees',
      description: 'Making structured decisions and flowcharts',
      category: 'Problem Solving',
      icon: iconMap['account_tree']!,
      estimatedMinutes: 35,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '47',
      title: 'Root Cause Analysis',
      description: 'Finding the real source of problems',
      category: 'Problem Solving',
      icon: iconMap['troubleshoot']!,
      estimatedMinutes: 40,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '48',
      title: 'Systems Thinking',
      description: 'Understanding interconnected systems',
      category: 'Problem Solving',
      icon: iconMap['hub']!,
      estimatedMinutes: 45,
      difficulty: 'Advanced',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '49',
      title: 'Scientific Method',
      description: 'Hypothesis, experiment, and conclusion',
      category: 'STEM Basics',
      icon: iconMap['science_outlined']!,
      estimatedMinutes: 30,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '50',
      title: 'Basic Coding Logic',
      description: 'Loops, conditions, and variables explained',
      category: 'STEM Basics',
      icon: iconMap['code']!,
      estimatedMinutes: 40,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '51',
      title: 'Data Types & Structures',
      description: 'Numbers, strings, lists, and objects',
      category: 'STEM Basics',
      icon: iconMap['data_object']!,
      estimatedMinutes: 35,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '52',
      title: 'Engineering Design',
      description: 'Design process from concept to prototype',
      category: 'STEM Basics',
      icon: iconMap['engineering']!,
      estimatedMinutes: 45,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '53',
      title: 'Measurement & Units',
      description: 'Metric system, conversions, and precision',
      category: 'STEM Basics',
      icon: iconMap['straighten']!,
      estimatedMinutes: 25,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '54',
      title: 'Electricity Basics',
      description: 'Voltage, current, resistance, and circuits',
      category: 'STEM Basics',
      icon: iconMap['electrical_services']!,
      estimatedMinutes: 40,
      difficulty: 'Beginner',
      createdAt: DateTime.now(),
    ),
    Topic(
      id: '55',
      title: 'Robotics Introduction',
      description: 'Sensors, actuators, and automation',
      category: 'STEM Basics',
      icon: iconMap['smart_toy']!,
      estimatedMinutes: 50,
      difficulty: 'Intermediate',
      createdAt: DateTime.now(),
    ),
  ];

  print('Starting to upload ${topics.length} topics...');

  int successCount = 0;
  int failCount = 0;

  for (final topic in topics) {
    try {
      await firestoreService.addTopic(topic);
      successCount++;
      print('✓ Uploaded: ${topic.title}');
    } catch (e) {
      failCount++;
      print('✗ Failed to upload ${topic.title}: $e');
    }
  }

  print('\n=== Upload Summary ===');
  print('Total topics: ${topics.length}');
  print('Successfully uploaded: $successCount');
  print('Failed: $failCount');
  print('======================\n');

  print('Upload process completed!');
}
