import 'dart:io';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'lib/firebase_options.dart';

Future<void> main() async {
  print('Starting Firebase initialization...');

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.web,
  );

  print('Firebase initialized successfully');

  final firestore = FirebaseFirestore.instance;

  final topics = [
    {
      'id': '1',
      'title': 'Flutter Basics',
      'description': 'Learn the fundamentals of Flutter development',
      'category': 'Programming',
      'iconCodePoint': 0xe32c,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 30,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '2',
      'title': 'State Management',
      'description': 'Master state management with Provider and Riverpod',
      'category': 'Programming',
      'iconCodePoint': 0xe8b9,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '3',
      'title': 'REST APIs',
      'description': 'Understanding and working with REST APIs',
      'category': 'Programming',
      'iconCodePoint': 0xe2bd,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '4',
      'title': 'Firebase Integration',
      'description': 'Integrate Firebase services in your Flutter app',
      'category': 'Programming',
      'iconCodePoint': 0xef3f,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 50,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '5',
      'title': 'Custom Animations',
      'description': 'Create beautiful custom animations in Flutter',
      'category': 'Programming',
      'iconCodePoint': 0xe71c,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 35,
      'difficulty': 'Advanced',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '6',
      'title': 'Material Design',
      'description': 'Implement Material Design principles',
      'category': 'Programming',
      'iconCodePoint': 0xef3e,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 25,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '7',
      'title': 'Responsive Layouts',
      'description': 'Build responsive UIs for all screen sizes',
      'category': 'Programming',
      'iconCodePoint': 0xe1b1,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 30,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '8',
      'title': 'Local Database',
      'description': 'Work with SQLite and local storage',
      'category': 'Programming',
      'iconCodePoint': 0xe1db,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '9',
      'title': 'Testing in Flutter',
      'description': 'Write unit, widget, and integration tests',
      'category': 'Programming',
      'iconCodePoint': 0xe868,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Advanced',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '10',
      'title': 'App Deployment',
      'description': 'Deploy your app to App Store and Play Store',
      'category': 'Programming',
      'iconCodePoint': 0xe255,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 60,
      'difficulty': 'Advanced',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '11',
      'title': 'Dart Fundamentals',
      'description': 'Syntax, types, collections, and async in Dart',
      'category': 'Programming',
      'iconCodePoint': 0xe86f,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '12',
      'title': 'Clean Architecture',
      'description': 'Layered architecture patterns for Flutter apps',
      'category': 'Programming',
      'iconCodePoint': 0xe8ef,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 50,
      'difficulty': 'Advanced',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '13',
      'title': 'CI/CD with GitHub Actions',
      'description': 'Automate build, test and deploy for Flutter',
      'category': 'Programming',
      'iconCodePoint': 0xe627,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 55,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '14',
      'title': 'Accessibility',
      'description': 'Build accessible apps with a11y best practices',
      'category': 'Programming',
      'iconCodePoint': 0xe84e,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 30,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '15',
      'title': 'Security Basics',
      'description': 'Secure storage, auth, and network in apps',
      'category': 'Programming',
      'iconCodePoint': 0xe32a,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '16',
      'title': 'Time Management',
      'description': 'Master productivity and time organization skills',
      'category': 'Life Skills',
      'iconCodePoint': 0xe8b5,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 35,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '17',
      'title': 'Communication Skills',
      'description': 'Effective verbal and written communication',
      'category': 'Life Skills',
      'iconCodePoint': 0xe0b7,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '18',
      'title': 'Financial Literacy',
      'description': 'Budgeting, saving, and basic personal finance',
      'category': 'Life Skills',
      'iconCodePoint': 0xe850,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '19',
      'title': 'Critical Thinking',
      'description': 'Develop analytical and problem-solving skills',
      'category': 'Life Skills',
      'iconCodePoint': 0xea4a,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '20',
      'title': 'Physics Fundamentals',
      'description': 'Newton\'s laws, energy, and motion',
      'category': 'Science',
      'iconCodePoint': 0xeacc,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 50,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '21',
      'title': 'Chemistry Basics',
      'description': 'Elements, compounds, and chemical reactions',
      'category': 'Science',
      'iconCodePoint': 0xe002,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '22',
      'title': 'Biology Introduction',
      'description': 'Cell structure, genetics, and ecosystems',
      'category': 'Science',
      'iconCodePoint': 0xeb52,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '23',
      'title': 'Environmental Science',
      'description': 'Climate change, sustainability, and ecology',
      'category': 'Science',
      'iconCodePoint': 0xea35,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 35,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '24',
      'title': 'World History',
      'description': 'Major civilizations and historical events',
      'category': 'Arts & Humanities',
      'iconCodePoint': 0xe80b,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 50,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '25',
      'title': 'Philosophy Basics',
      'description': 'Ethics, logic, and major philosophical ideas',
      'category': 'Arts & Humanities',
      'iconCodePoint': 0xe0c0,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '26',
      'title': 'Creative Writing',
      'description': 'Storytelling, character development, and narrative',
      'category': 'Arts & Humanities',
      'iconCodePoint': 0xe3c9,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '27',
      'title': 'Art History',
      'description': 'Major art movements and influential artists',
      'category': 'Arts & Humanities',
      'iconCodePoint': 0xe40a,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 35,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '28',
      'title': 'Algebra Fundamentals',
      'description': 'Equations, variables, and functions',
      'category': 'Math',
      'iconCodePoint': 0xea5f,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '29',
      'title': 'Geometry Basics',
      'description': 'Shapes, angles, and spatial reasoning',
      'category': 'Math',
      'iconCodePoint': 0xea3b,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '30',
      'title': 'Statistics & Probability',
      'description': 'Data analysis and probability theory',
      'category': 'Math',
      'iconCodePoint': 0xe26b,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 50,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '31',
      'title': 'Calculus Introduction',
      'description': 'Limits, derivatives, and integrals',
      'category': 'Math',
      'iconCodePoint': 0xe24d,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 60,
      'difficulty': 'Advanced',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '32',
      'title': 'Microeconomics',
      'description': 'Supply, demand, and market structures',
      'category': 'Economics',
      'iconCodePoint': 0xe8d1,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '33',
      'title': 'Macroeconomics',
      'description': 'GDP, inflation, and economic policies',
      'category': 'Economics',
      'iconCodePoint': 0xe8e5,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 50,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '34',
      'title': 'Personal Finance',
      'description': 'Investing, retirement planning, and wealth building',
      'category': 'Economics',
      'iconCodePoint': 0xe2eb,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '35',
      'title': 'Business Economics',
      'description': 'Cost analysis, pricing strategies, and profit',
      'category': 'Economics',
      'iconCodePoint': 0xe0ca,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '36',
      'title': 'Internet Safety',
      'description': 'Privacy, online security, and safe browsing',
      'category': 'Digital Literacy',
      'iconCodePoint': 0xe32a,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 30,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '37',
      'title': 'Email & Communication',
      'description': 'Professional emails, online etiquette, and tools',
      'category': 'Digital Literacy',
      'iconCodePoint': 0xe0be,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 25,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '38',
      'title': 'Search Skills',
      'description': 'Effective web searching and information evaluation',
      'category': 'Digital Literacy',
      'iconCodePoint': 0xe8b6,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 20,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '39',
      'title': 'Cloud Storage',
      'description': 'Google Drive, Dropbox, and file management',
      'category': 'Digital Literacy',
      'iconCodePoint': 0xe2c3,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 30,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '40',
      'title': 'Social Media Literacy',
      'description': 'Responsible use and avoiding misinformation',
      'category': 'Digital Literacy',
      'iconCodePoint': 0xe80d,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 35,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '41',
      'title': 'Password Management',
      'description': 'Creating strong passwords and using managers',
      'category': 'Digital Literacy',
      'iconCodePoint': 0xe0da,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 25,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '42',
      'title': 'Digital Footprint',
      'description': 'Online reputation and personal branding',
      'category': 'Digital Literacy',
      'iconCodePoint': 0xe90d,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 30,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '43',
      'title': 'Logical Reasoning',
      'description': 'Deductive and inductive reasoning patterns',
      'category': 'Problem Solving',
      'iconCodePoint': 0xe0f0,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 35,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '44',
      'title': 'Algorithmic Thinking',
      'description': 'Breaking down problems into steps',
      'category': 'Problem Solving',
      'iconCodePoint': 0xe8e6,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '45',
      'title': 'Pattern Recognition',
      'description': 'Identifying patterns in data and sequences',
      'category': 'Problem Solving',
      'iconCodePoint': 0xe9bc,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 30,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '46',
      'title': 'Decision Trees',
      'description': 'Making structured decisions and flowcharts',
      'category': 'Problem Solving',
      'iconCodePoint': 0xe8ef,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 35,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '47',
      'title': 'Root Cause Analysis',
      'description': 'Finding the real source of problems',
      'category': 'Problem Solving',
      'iconCodePoint': 0xe75e,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '48',
      'title': 'Systems Thinking',
      'description': 'Understanding interconnected systems',
      'category': 'Problem Solving',
      'iconCodePoint': 0xe9f4,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Advanced',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '49',
      'title': 'Scientific Method',
      'description': 'Hypothesis, experiment, and conclusion',
      'category': 'STEM Basics',
      'iconCodePoint': 0xeacc,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 30,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '50',
      'title': 'Basic Coding Logic',
      'description': 'Loops, conditions, and variables explained',
      'category': 'STEM Basics',
      'iconCodePoint': 0xe86f,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '51',
      'title': 'Data Types & Structures',
      'description': 'Numbers, strings, lists, and objects',
      'category': 'STEM Basics',
      'iconCodePoint': 0xef24,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 35,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '52',
      'title': 'Engineering Design',
      'description': 'Design process from concept to prototype',
      'category': 'STEM Basics',
      'iconCodePoint': 0xea3d,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 45,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '53',
      'title': 'Measurement & Units',
      'description': 'Metric system, conversions, and precision',
      'category': 'STEM Basics',
      'iconCodePoint': 0xe3d0,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 25,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '54',
      'title': 'Electricity Basics',
      'description': 'Voltage, current, resistance, and circuits',
      'category': 'STEM Basics',
      'iconCodePoint': 0xec0c,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 40,
      'difficulty': 'Beginner',
      'createdAt': FieldValue.serverTimestamp(),
    },
    {
      'id': '55',
      'title': 'Robotics Introduction',
      'description': 'Sensors, actuators, and automation',
      'category': 'STEM Basics',
      'iconCodePoint': 0xea48,
      'iconFontFamily': 'MaterialIcons',
      'estimatedMinutes': 50,
      'difficulty': 'Intermediate',
      'createdAt': FieldValue.serverTimestamp(),
    },
  ];

  print('Starting to upload ${topics.length} topics...');

  int successCount = 0;
  int failCount = 0;

  for (final topic in topics) {
    try {
      await firestore
          .collection('topics')
          .doc(topic['id'] as String)
          .set(topic);
      successCount++;
      print('✓ Uploaded: ${topic['title']}');
    } catch (e) {
      failCount++;
      print('✗ Failed to upload ${topic['title']}: $e');
    }
  }

  print('\n=== Upload Summary ===');
  print('Total topics: ${topics.length}');
  print('Successfully uploaded: $successCount');
  print('Failed: $failCount');
  print('======================\n');

  print('Upload process completed!');

  exit(0);
}
