// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUK7Tqltu29luyvRM9s-rxLXrfg6pSloA',
    appId: '1:1056660119849:web:64806579c8bd0e69bbd738',
    messagingSenderId: '1056660119849',
    projectId: 'plp-ai-tutor',
    authDomain: 'plp-ai-tutor.firebaseapp.com',
    storageBucket: 'plp-ai-tutor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUK7Tqltu29luyvRM9s-rxLXrfg6pSloA',
    appId: '1:1056660119849:android:64806579c8bd0e69bbd738',
    messagingSenderId: '1056660119849',
    projectId: 'plp-ai-tutor',
    storageBucket: 'plp-ai-tutor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUK7Tqltu29luyvRM9s-rxLXrfg6pSloA',
    appId: '1:1056660119849:ios:64806579c8bd0e69bbd738',
    messagingSenderId: '1056660119849',
    projectId: 'plp-ai-tutor',
    storageBucket: 'plp-ai-tutor.firebasestorage.app',
    iosBundleId: 'com.example.aiTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUK7Tqltu29luyvRM9s-rxLXrfg6pSloA',
    appId: '1:1056660119849:ios:64806579c8bd0e69bbd738',
    messagingSenderId: '1056660119849',
    projectId: 'plp-ai-tutor',
    storageBucket: 'plp-ai-tutor.firebasestorage.app',
    iosBundleId: 'com.example.aiTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUK7Tqltu29luyvRM9s-rxLXrfg6pSloA',
    appId: '1:1056660119849:web:64806579c8bd0e69bbd738',
    messagingSenderId: '1056660119849',
    projectId: 'plp-ai-tutor',
    authDomain: 'plp-ai-tutor.firebaseapp.com',
    storageBucket: 'plp-ai-tutor.firebasestorage.app',
  );
}
