// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8S5o5VxWtUzXDksjoITGm3s7NyxYP8Vs',
    appId: '1:209455312625:web:cad8f86499d72871e04350',
    messagingSenderId: '209455312625',
    projectId: 'ai-tutor-cedad',
    authDomain: 'ai-tutor-cedad.firebaseapp.com',
    storageBucket: 'ai-tutor-cedad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8S5o5VxWtUzXDksjoITGm3s7NyxYP8Vs',
    appId: '1:209455312625:android:cad8f86499d72871e04350',
    messagingSenderId: '209455312625',
    projectId: 'ai-tutor-cedad',
    storageBucket: 'ai-tutor-cedad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8S5o5VxWtUzXDksjoITGm3s7NyxYP8Vs',
    appId: '1:209455312625:ios:cad8f86499d72871e04350',
    messagingSenderId: '209455312625',
    projectId: 'ai-tutor-cedad',
    storageBucket: 'ai-tutor-cedad.firebasestorage.app',
    iosBundleId: 'com.example.aiTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8S5o5VxWtUzXDksjoITGm3s7NyxYP8Vs',
    appId: '1:209455312625:ios:cad8f86499d72871e04350',
    messagingSenderId: '209455312625',
    projectId: 'ai-tutor-cedad',
    storageBucket: 'ai-tutor-cedad.firebasestorage.app',
    iosBundleId: 'com.example.aiTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8S5o5VxWtUzXDksjoITGm3s7NyxYP8Vs',
    appId: '1:209455312625:web:cad8f86499d72871e04350',
    messagingSenderId: '209455312625',
    projectId: 'ai-tutor-cedad',
    authDomain: 'ai-tutor-cedad.firebaseapp.com',
    storageBucket: 'ai-tutor-cedad.firebasestorage.app',
  );
}
